[build]
  functions = "functions"
[[redirects]]
  from = "/"
  to = ".netlify/functions/metafetcher"
  status = 200
[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = “GET, POST, OPTION”